# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/leds.xdc

# Block Designs: bd/CoreSight_Decode/CoreSight_Decode.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CoreSight_Decode || ORIG_REF_NAME==CoreSight_Decode} -quiet] -quiet

# IP: bd/CoreSight_Decode/ip/CoreSight_Decode_zynq_ultra_ps_e_0_0/CoreSight_Decode_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CoreSight_Decode_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==CoreSight_Decode_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/CoreSight_Decode/ip/CoreSight_Decode_Decoder_Debugger_0_0/CoreSight_Decode_Decoder_Debugger_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CoreSight_Decode_Decoder_Debugger_0_0 || ORIG_REF_NAME==CoreSight_Decode_Decoder_Debugger_0_0} -quiet] -quiet

# IP: bd/CoreSight_Decode/ip/CoreSight_Decode_CoreSight_L0_Decoder_0_0/CoreSight_Decode_CoreSight_L0_Decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CoreSight_Decode_CoreSight_L0_Decoder_0_0 || ORIG_REF_NAME==CoreSight_Decode_CoreSight_L0_Decoder_0_0} -quiet] -quiet

# XDC: /home/marvin/VivadoPrj/CoreSight_Decoder/CoreSight_Decoder.gen/sources_1/bd/CoreSight_Decode/CoreSight_Decode_ooc.xdc
