#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 21 16:44:46 CST 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim CoreSight_L2_Deocde_lee_sim_behav -key {Behavioral:sim_1:Functional:CoreSight_L2_Deocde_lee_sim} -tclbatch CoreSight_L2_Deocde_lee_sim.tcl -protoinst "protoinst_files/CoreSight_Decode.protoinst" -view /home/marvin/VivadoPrj/CoreSight_Decoder/CoreSight_L2_Decoder_lee_sim_behav.wcfg -log simulate.log"
xsim CoreSight_L2_Deocde_lee_sim_behav -key {Behavioral:sim_1:Functional:CoreSight_L2_Deocde_lee_sim} -tclbatch CoreSight_L2_Deocde_lee_sim.tcl -protoinst "protoinst_files/CoreSight_Decode.protoinst" -view /home/marvin/VivadoPrj/CoreSight_Decoder/CoreSight_L2_Decoder_lee_sim_behav.wcfg -log simulate.log

